name = "up-down-workers"
main = "build/worker/shim.mjs"
compatibility_date = "2025-07-01"

[build]
command = "cargo install -q worker-build && worker-build --release"

[vars]
# CACHE_TTL_SECONDS = 600
